# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MTK_LEDS) := mtk_leds.o

ccflags-y += -I$(srctree)/drivers/misc/mediatek/video/include
#Liverpool code for AX3207-347 by liruiju at 20-11-13 start
ccflags-y += -I$(srctree)/drivers/power/supply
#Liverpool code for AX3207-347 by liruiju at 20-11-13 end